language: go

env:
  - DEP_VERSION="v0.3.2"

go:
  - 1.9.x

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep


install:
  - $GOPATH/bin/dep ensure

script:
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)